name: Auto rebase on workflow_dispatch

on: workflow_dispatch
env:
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ env.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
        if: ${{ env.PERSONAL_ACCESS_TOKEN != '' }}
      - name: Debug
        run: echo cat $GITHUB_EVENT_PATH
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.4
        env:
          GITHUB_TOKEN: ${{ env.PERSONAL_ACCESS_TOKEN }}
        if: ${{ env.PERSONAL_ACCESS_TOKEN != '' }}
      - name: Send failure message
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Automatic rebasing for this issue has failed :disappointed:

            You'll have to rebase this one manually, I'm afraid.
        if: ${{ failure() }}
