name: Automatic Rebase
on:
  issue_comment:
    types: [created]
env:
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
jobs:
  check_token:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase') && env.PERSONAL_ACCESS_TOKEN == ''
    runs-on: ubuntu-latest
    steps:
      - name: Prompt user to add a token
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            To automatically rebase, you need to add a personal access token with the name `PERSONAL_ACCESS_TOKEN`
            to the [secrets section of this repo](https://github.com/${{ github.event.repository.full_name }}/settings/secrets/actions).
        if: ${{ failure() }}
  reaction:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase') && env.PERSONAL_ACCESS_TOKEN != ''
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: "+1"
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase') && env.PERSONAL_ACCESS_TOKEN != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ env.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.4
        env:
          GITHUB_TOKEN: ${{ env.PERSONAL_ACCESS_TOKEN }}
      - name: Send failure message
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Automatic rebasing for this issue has failed :disappointed:

            You'll have to rebase this one manually, I'm afraid.
        if: ${{ failure() }}
