name: Automatic Rebase
on:
  issue_comment:
    types: [created]
env:
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  triggered_by_comment: ${{ github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase') }}
jobs:
  check_token:
    if: ${{ env.triggered_by_comment }}
    runs-on: ubuntu-latest
    steps:
      - name: Prompt user to add a token
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            To automatically rebase, you need to add a [personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) with the name `PERSONAL_ACCESS_TOKEN`
            to the [secrets section of this repo](https://github.com/${{ github.event.repository.full_name }}/settings/secrets/actions).

            Once this is done, you can try the command again.
        if: ${{ env.PERSONAL_ACCESS_TOKEN == '' }}
      - name: Add -1 reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: "-1"
        if: ${{ env.PERSONAL_ACCESS_TOKEN == '' }}
      - name: Add +1 reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: "+1"
        if: ${{ env.PERSONAL_ACCESS_TOKEN != '' }}
  rebase:
    if: ${{ env.triggered_by_comment }}
    name: Rebase
    needs: check_token
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ env.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
        if: ${{ env.PERSONAL_ACCESS_TOKEN != '' }}
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.4
        env:
          GITHUB_TOKEN: ${{ env.PERSONAL_ACCESS_TOKEN }}
        if: ${{ env.PERSONAL_ACCESS_TOKEN != '' }}
      - name: Send failure message
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Automatic rebasing for this issue has failed :disappointed:

            You'll have to rebase this one manually, I'm afraid.
        if: ${{ failure() }}
