name: Trigger auto rebase

on: pull_request_target:
      types: [auto_merge_enabled]

jobs:
  trigger_auto_rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Auto Rebase
        uses: dxw/trigger-action-on-automerge-prs@main
        with:
          personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow: "rebase.yml"
