name: Trigger auto rebase

on:
  push:
    branches:
      - master

jobs:
  trigger_auto_rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Auto Rebase
        uses: dxw/trigger-action-on-automerge-prs@main
        with:
          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow: "rebase.yml"
