name: Trigger auto rebase

on:
  push:
    branches:
      - master
# Can we set automerge as a trigger?

jobs:
  trigger_auto_rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Auto Rebase
        uses: dxw/trigger-action-on-automerge-prs@debug
        with:
          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow: "auto-rebase.yml"
